version: '3.7'

services:
  moodle:
    build: .
    ports:
      - "8080:80"
    volumes:
      - moodledata:/var/www/moodledata
      - ./config.php:/var/www/html/config.php
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepassword
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  moodledata:
  dbdata:
